services:
  postgres:
    container_name: jwt_app_postgres
    image: postgres
    environment:
      POSTGRES_USER: efexunn
      POSTGRES_PASSWORD: efexunn
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - jwt-app
    restart: unless-stopped


networks:
  jwt-app:
    driver: bridge

volumes:
  postgres:
